# Data exploration and transformation for jobspy query output

In this notebook, the output from Jobspy will be explored and cleaned in a way that will be general for the processing of the data.

## General goal

The general goal of the dashboard is to viasually analyse the status of the job market in a specific (or various) European countries and per industry (or job title). For doing this, an open-source library [(JobSpy)](https://github.com/cullenwatson/JobSpy) is used to scrape data from the most popular job-posting sites, **Indeed** and **Glassdoor**.

THe first step is to check what is the data that is gathered from the query, to select the interesting or most populated features, and to remove duplicates between pages.

In [2]:
from jobspy import scrape_jobs

In [3]:
country = 'Spain'
jobs = scrape_jobs(
    site_name=[
        "indeed",
        "glassdoor"
    ],
    search_term="data science",
    location=country,
    results_wanted=200,
    hours_old=72,
    country_indeed=country
)

2025-03-13 13:03:06,340 - INFO - JobSpy:Indeed - search page: 1 / 2
2025-03-13 13:03:07,277 - INFO - JobSpy:Indeed - search page: 2 / 2
2025-03-13 13:03:07,348 - INFO - JobSpy:Glassdoor - search page: 1 / 7
2025-03-13 13:03:09,049 - INFO - JobSpy:Indeed - search page: 3 / 2
2025-03-13 13:03:09,395 - INFO - JobSpy:Glassdoor - search page: 2 / 7
2025-03-13 13:03:09,580 - INFO - JobSpy:Indeed - found no jobs on page: 3
2025-03-13 13:03:09,581 - INFO - JobSpy:Indeed - finished scraping
2025-03-13 13:03:11,240 - INFO - JobSpy:Glassdoor - search page: 3 / 7
2025-03-13 13:03:12,593 - INFO - JobSpy:Glassdoor - search page: 4 / 7
2025-03-13 13:03:13,841 - INFO - JobSpy:Glassdoor - search page: 5 / 7
2025-03-13 13:03:15,278 - INFO - JobSpy:Glassdoor - search page: 6 / 7
2025-03-13 13:03:16,893 - INFO - JobSpy:Glassdoor - search page: 7 / 7
2025-03-13 13:03:17,407 - INFO - JobSpy:Glassdoor - finished scraping

In [4]:
jobs.head(10)

,id,site,job_url,job_url_direct,title,company,location,date_posted,job_type,salary_source,...,emails,description,company_industry,company_url,company_logo,company_url_direct,company_addresses,company_num_employees,company_revenue,company_description
0,gd-1009670311645,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,Services Delivery Manager,Westcon-Comstor,Madrid,2025-03-13,NaN,NaN,...,NaN,Westcon\-Comstor (WestconGroup Inc.) is a glob...,NaN,https://www.glassdoor.es/Overview/W-EI_IE11239...,https://media.glassdoor.com/sql/11239/westcon-...,NaN,NaN,NaN,NaN,NaN
1,gd-1009670427615,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,Associate - Reference Data Analyst,MSCI,España,2025-03-13,NaN,NaN,...,Disability.Assistance@msci.com,Associate \- Reference Data Analyst**Your Team...,NaN,https://www.glassdoor.es/Overview/W-EI_IE14616...,https://media.glassdoor.com/sql/14616/msci-squ...,NaN,NaN,NaN,NaN,NaN
2,gd-1009670581096,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,Senior Data Engineer (m/f/d),Digistore24,España,2025-03-13,NaN,NaN,...,NaN,**The Data engineer supports the data team to ...,NaN,https://www.glassdoor.es/Overview/W-EI_IE39147...,https://media.glassdoor.com/sql/3914709/digist...,NaN,NaN,NaN,NaN,NaN
3,gd-1009670391207,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,MSL Hematología L - Barcelona,Johnson & Johnson,España,2025-03-13,NaN,NaN,...,NaN,"At Johnson \& Johnson, we believe health is ev...",NaN,https://www.glassdoor.es/Overview/W-EI_IE364.htm,https://media.glassdoor.com/sql/364/johnson-an...,NaN,NaN,NaN,NaN,NaN
4,gd-1009670933847,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,Project Assistant,Barcelona Institute for Global Health (ISGlobal),Barcelona,2025-03-13,NaN,NaN,...,NaN,The Barcelona Institute for Global Health (ISG...,NaN,https://www.glassdoor.es/Overview/W-EI_IE20535...,https://media.glassdoor.com/sql/2053559/isglob...,NaN,NaN,NaN,NaN,NaN
5,gd-1009670748843,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,Marketing Data Analyst,Livo,Barcelona,2025-03-13,NaN,NaN,...,NaN,#### **Your mission**\n\n**Your mission**\n===...,NaN,https://www.glassdoor.es/Overview/W-EI_IE78701...,NaN,NaN,NaN,NaN,NaN,NaN
6,gd-1009671459252,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,Business Development,EF Polymer(株),NaN,2025-03-13,NaN,direct_data,...,NaN,▼ Background of the Application\n\nEF Polymer ...,NaN,https://www.glassdoor.es/Overview/W-EI_IE95433...,NaN,NaN,NaN,NaN,NaN,NaN
7,gd-1009670632929,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,AI Engineer,Grupo Lanit,España,2025-03-13,NaN,NaN,...,NaN,DESCRIPCIóN\n\n\n¿Te gusta la tecnología? ¿Qui...,NaN,https://www.glassdoor.es/Overview/W-EI_IE43887...,https://media.glassdoor.com/sql/4388758/lanit-...,NaN,NaN,NaN,NaN,NaN
8,gd-1009670989060,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,Senior Data Scientist,Rover.com,Barcelona,2025-03-13,NaN,NaN,...,NaN,**Who we are:**\nWant to make an impact? Join ...,NaN,https://www.glassdoor.es/Overview/W-EI_IE71047...,https://media.glassdoor.com/sql/710477/rover-c...,NaN,NaN,NaN,NaN,NaN
9,gd-1009670821913,glassdoor,https://www.glassdoor.es/job-listing/j?jl=1009...,NaN,Expert Data Scientist - Advanced Analytics & I...,Nestlé,España,2025-03-13,NaN,NaN,...,NaN,We are looking for someone with strong analyti...,NaN,https://www.glassdoor.es/Overview/W-EI_IE4283.htm,https://media.glassdoor.com/sql/4283/nestlé-us...,NaN,NaN,NaN,NaN,NaN

In [5]:
jobs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 371 entries, 0 to 370
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     371 non-null    object
 1   site                   371 non-null    object
 2   job_url                371 non-null    object
 3   job_url_direct         195 non-null    object
 4   title                  371 non-null    object
 5   company                367 non-null    object
 6   location               360 non-null    object
 7   date_posted            371 non-null    object
 8   job_type               134 non-null    object
 9   salary_source          4 non-null      object
 10  interval               4 non-null      object
 11  min_amount             4 non-null      float64
 12  max_amount             4 non-null      float64
 13  currency               4 non-null      object
 14  is_remote              371 non-null    bool
 15  job_level              0 non-null      object
 16  job_function           0 non-null      object
 17  listing_type           176 non-null    object
 18  emails                 29 non-null     object
 19  description            371 non-null    object
 20  company_industry       33 non-null     object
 21  company_url            365 non-null    object
 22  company_logo           310 non-null    object
 23  company_url_direct     162 non-null    object
 24  company_addresses      147 non-null    object
 25  company_num_employees  154 non-null    object
 26  company_revenue        131 non-null    object
 27  company_description    121 non-null    object
dtypes: bool(1), float64(2), object(25)
memory usage: 78.7+ KB

We are interested in checking and analysing the description, among others. Therefore, empty descriptions should be removed:

In [6]:
empty_des = jobs.loc[jobs.description.isna()].index
jobs.drop(empty_des, axis=0, inplace=True)

In [7]:
# Select columns with non-null values and drop the ones not having full rows
cols = ['id','site', 'title', 'company', 'location', 'date_posted', 'job_url', 'description']
jobs_red = jobs[cols].dropna().reset_index(drop=True)

In [8]:
jobs_red.location.unique()

array(['Madrid', 'España', 'Barcelona', 'Granada', 'Las Palmas', 'Getafe',
       'Vila-seca', 'Cerdanyola del Vallès', 'Badalona',
       'Boadilla del Monte', 'Vila-seca, CT, ES', 'Madrid, MD, ES',
       'En remoto, ES', 'Barcelona, CT, ES',
       'Santa Cruz de Tenerife, CN, ES',
       'Las Palmas de Gran Canaria, CN, ES', 'San Adrián, NC, ES',
       'Esplugues de Llobregat, CT, ES', 'ES', 'Getafe, MD, ES',
       'Granada, AN, ES', 'Cornellà de Llobregat, CT, ES',
       'Sant Cugat del Vallès, CT, ES', 'Verín, GA, ES',
       'La Moraleja, MD, ES', 'MD, ES', 'Málaga, AN, ES',
       'Sant Just Desvern, CT, ES', 'Parets del Vallès, CT, ES',
       'Barcenilla, CB, ES', 'Tratamiento De Aguas (Goloso, El), MD, ES',
       'Badalona, CT, ES', 'CT, ES', 'Cerdanyola del Vallès, CT, ES',
       'VC, ES', 'AS, ES', 'Boadilla del Monte, MD, ES',
       'A Coruña, GA, ES', 'Valencia, VC, ES', 'Bilbao, PV, ES',
       'Sevilla, AN, ES', 'Tres Cantos, MD, ES', 'Leganés, MD, ES',
       'GA, ES'], dtype=object)

In [9]:
jobs_red.groupby('site').count()

            id  title  company  location  date_posted  job_url  description
site
glassdoor  165    165      165       165          165      165          165
indeed     191    191      191       191          191      191          191

In [10]:
duplicates = jobs_red[['company', 'title']].duplicated()
dup_df = jobs_red.loc[duplicates]
dup_df.groupby('site').count()

         id  title  company  location  date_posted  job_url  description
site
indeed  120    120      120       120          120      120          120

In [11]:
remove_index = []
for index, row in dup_df.iterrows():
    temp_dup = jobs_red.loc[(jobs_red.company==row['company']) & (jobs_red.title==row['title'])]
    # If there are duplicates between sites, remove glassdoor:
    if (('indeed' in temp_dup['site'].unique()) & ('glassdoor' in temp_dup['site'].unique())):
        remove_index.append(temp_dup.loc[temp_dup['site']=='glassdoor'].index.item())
print(remove_index)

[34, 33, 32, 21, 18, 18, 33, 19, 19, 7, 28, 35, 47, 5, 48, 17, 12, 54, 6, 29, 25, 16, 30, 41, 24, 24, 3, 23, 51, 13, 22, 39, 20, 7, 11, 1, 31, 61, 87, 74, 79, 82, 106, 88, 80, 67, 66, 78, 86, 97, 107, 65, 93, 90, 81, 57, 59, 68, 58, 72, 100, 134, 155, 104, 71, 98, 98, 128, 135, 125, 156, 164, 136, 120, 160, 146, 143, 124, 110, 145, 139, 121, 123, 116, 126, 147, 163, 159, 157, 154, 149, 150, 148, 115, 114, 118, 152, 162, 137, 160, 122, 112, 129, 70, 77, 77, 77, 77, 77, 77, 132, 27, 2]

In [12]:
jobs_red.loc[remove_index,:].head()

,id,site,title,company,location,date_posted,job_url,description
34,gd-1009671806990,glassdoor,Senior SAP Consultant,Messer Ibérica,Vila-seca,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,"**As a global player, Messer offers its sustai..."
33,gd-1009671401481,glassdoor,Sr Program Manager,Dow Jones,Barcelona,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,\*\*About Our Organization:\*\*\n\n\n\nDow Jon...
32,gd-1009671308575,glassdoor,Operations Research & Applied Intelligence Man...,Pfizer,Madrid,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,Context\nPfizer Global Supply (PGS) is the par...
21,gd-1009671290157,glassdoor,Testing Technician- Energías Renovables,Enertis Applus+,Madrid,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,**Enertis Applus\+** es una firma global de Co...
18,gd-1009671244143,glassdoor,Vaccines Account Specialist - Canarias,GSK,Las Palmas,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,**Site Name:** Spain \- Canarias \- Las Palmas...

In [13]:
final_jobs = jobs_red.drop(remove_index, axis=0)

In [14]:
final_jobs.drop('site', axis=1, inplace=True)

Location in glassdoor contains city, region and country code. Let's divide this in city and country (coming from selected query in jobspy)

In [15]:
final_jobs['city'] = final_jobs['location'].str.split(',').str[0]
final_jobs['country'] = country
final_jobs.drop('location', axis=1, inplace=True)

In [16]:
final_jobs.groupby('city').count()

,id,title,company,date_posted,job_url,description,country
city,,,,,,,
A Coruña,4,4,4,4,4,4,4
AS,1,1,1,1,1,1,1
Badalona,2,2,2,2,2,2,2
Barcelona,98,98,98,98,98,98,98
Barcenilla,1,1,1,1,1,1,1
Bilbao,1,1,1,1,1,1,1
Boadilla del Monte,2,2,2,2,2,2,2
CT,1,1,1,1,1,1,1
Cerdanyola del Vallès,2,2,2,2,2,2,2
Cornellà de Llobregat,1,1,1,1,1,1,1
ES,5,5,5,5,5,5,5
En remoto,11,11,11,11,11,11,11
España,12,12,12,12,12,12,12
Esplugues de Llobregat,2,2,2,2,2,2,2
GA,1,1,1,1,1,1,1
Getafe,4,4,4,4,4,4,4
Granada,6,6,6,6,6,6,6
La Moraleja,1,1,1,1,1,1,1
Las Palmas de Gran Canaria,1,1,1,1,1,1,1
Leganés,1,1,1,1,1,1,1
MD,1,1,1,1,1,1,1
Madrid,77,77,77,77,77,77,77
Málaga,1,1,1,1,1,1,1
Parets del Vallès,1,1,1,1,1,1,1
San Adrián,2,2,2,2,2,2,2
Sant Cugat del Vallès,3,3,3,3,3,3,3
Sant Just Desvern,2,2,2,2,2,2,2
Santa Cruz de Tenerife,1,1,1,1,1,1,1
Sevilla,1,1,1,1,1,1,1
Tratamiento De Aguas (Goloso,1,1,1,1,1,1,1
Tres Cantos,1,1,1,1,1,1,1
VC,1,1,1,1,1,1,1
Valencia,2,2,2,2,2,2,2
Verín,3,3,3,3,3,3,3
Vila-seca,1,1,1,1,1,1,1

In [17]:
final_jobs.head()

,id,title,company,date_posted,job_url,description,city,country
0,gd-1009670311645,Services Delivery Manager,Westcon-Comstor,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,Westcon\-Comstor (WestconGroup Inc.) is a glob...,Madrid,Spain
4,gd-1009670933847,Project Assistant,Barcelona Institute for Global Health (ISGlobal),2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,The Barcelona Institute for Global Health (ISG...,Barcelona,Spain
8,gd-1009670821913,Expert Data Scientist - Advanced Analytics & I...,Nestlé,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,We are looking for someone with strong analyti...,España,Spain
9,gd-1009670584344,DATA SCIENTIST AND MACHINE LEARNING ENGINEER (...,Centre Tecnologic de Catalunya,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,**EURECAT**\n-----------\n\n\nEurecat is the m...,Barcelona,Spain
10,gd-1009670390004,Data Migration Lead,strada,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,**Our story**\n\n\nStrada is a technology\-ena...,Granada,Spain

In [18]:
final_jobs.dtypes

id             object
title          object
company        object
date_posted    object
job_url        object
description    object
city           object
country        object
dtype: object

print(f"""
    Lengths for setting VARCHAR length in database: \n
    Title:\n {final_jobs.title.str.len().describe()} \n
    Company:\n {final_jobs.company.str.len().describe()} \n
    URL:\n {final_jobs.job_url.str.len().describe()} \n
    Description:\n {final_jobs.description.str.len().describe()} \n
    """)

Transforming the decription requires removing the markdown formating and unifying the language. Some description might be in a different language depending on the country we are querying, even if the search term is in English. To solve this problem and have a better overview of the descriptions in spite of the language, first the language of the description will be detected and then translated to English. In addition, the language of the ad will also be added as a feature.

In [19]:
# Remove markdown
# Dictionary of regex patterns to remove specific Markdown elements
markdown_removal_patterns = {
    r'(\*{1,2}|_{1,2})(.*?)\1': r'\2',  # Remove bold (**text**, __text__) and italics (*text*, _text_)
    r'\[([^\]]+)\]\([^)]+\)': r'\1',    # Remove links, keeping only the text
    r'https?://\S+': '',                # Remove standalone URLs
    r'\n': ' ',                         # Remove newlines and replace with a space
    r'\\': '',
    r'#': '',
    r'\*': '',
    r'\--': ''
}

final_jobs['description'].replace(markdown_removal_patterns, regex=True, inplace=True)

/var/folders/tn/__jkvfl15hz0hrlfh0307zkr0000gn/T/ipykernel_97647/3133261598.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  final_jobs['description'].replace(markdown_removal_patterns, regex=True, inplace=True)

In [20]:
# Detect language
from langdetect import detect

final_jobs['description_language'] = final_jobs.description.apply(lambda x: detect(x)).values

In [21]:
final_jobs.loc[final_jobs['description_language']!='en'].index

Index([64, 102, 105, 113, 173, 193, 219, 254, 279, 281, 315, 333], dtype='int64')

In [22]:
final_jobs.description.loc[final_jobs.description=='']

Series([], Name: description, dtype: object)

In [23]:
# Translate
from googletrans import Translator

translator = Translator()
index_nonen = final_jobs.loc[final_jobs['description_language']!='en'].index

for desc in final_jobs.loc[index_nonen, 'description'].values:
    try:
        translator.translate(desc, dest='en').text
    except:
        print(desc.__class__.__name__)

def translate_exception(text):
    try:
        return translator.translate(x, dest='en').text
    except:
        return None

final_jobs.loc[index_nonen, 'description'] = final_jobs.loc[index_nonen, 'description'].apply(lambda x: translate_exception(x))

str

In [24]:
final_jobs.dropna(subset='description', inplace=True)
final_jobs.description=final_jobs.description.str.lower()

In [25]:
final_jobs.head()

,id,title,company,date_posted,job_url,description,city,country,description_language
0,gd-1009670311645,Services Delivery Manager,Westcon-Comstor,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,westcon-comstor (westcongroup inc.) is a globa...,Madrid,Spain,en
4,gd-1009670933847,Project Assistant,Barcelona Institute for Global Health (ISGlobal),2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,the barcelona institute for global health (isg...,Barcelona,Spain,en
8,gd-1009670821913,Expert Data Scientist - Advanced Analytics & I...,Nestlé,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,we are looking for someone with strong analyti...,España,Spain,en
9,gd-1009670584344,DATA SCIENTIST AND MACHINE LEARNING ENGINEER (...,Centre Tecnologic de Catalunya,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,eurecat - eurecat is the main research & tec...,Barcelona,Spain,en
10,gd-1009670390004,Data Migration Lead,strada,2025-03-13,https://www.glassdoor.es/job-listing/j?jl=1009...,"our story strada is a technology-enabled, pe...",Granada,Spain,en

Load data into a sqlite database

In [26]:
import sqlite3

conn = sqlite3.connect("jobs.db")
cursor = conn.cursor()
# DROP TABLE
#cursor.execute("DROP TABLE jobspy")
#conn.commit()

# Create jobs table
cursor.execute("""
    CREATE TABLE IF NOT EXISTS jobspy (
        id TEXT PRIMARY KEY,
        title TEXT,
        company TEXT,
        date_posted TEXT,
        job_url TEXT,
        description TEXT,
        city TEXT,
        country TEXT,
        description_language TEXT
    )
""")
conn.commit()

In [27]:
ids = cursor.execute("SELECT id FROM jobspy").fetchall()

In [28]:
cursor.execute("SELECT count(*) FROM jobspy WHERE country='Austria' AND date_posted >= date('now', '-1 days');").fetchall()[0][0]

0

In [29]:
uniques = [x[0] for x in cursor.execute("SELECT DISTINCT(country) FROM jobspy").fetchall()]

In [30]:
unique_countries=['Austria', 'Spain', 'Germany']
i=1
#cursor.execute(f"""SELECT count(*) FROM jobspy WHERE country={unique_countries[i]} 
#            AND date_posted >= date('now', '-1 days');
#            """).fetchall()[0][0]
cursor.execute(f"""SELECT count(*) FROM jobspy WHERE country='Austria'
            AND date_posted >= date('now', '-1 days');
            """).fetchall()[0][0]

0

In [31]:
uniques

['Austria', 'Germany', 'Spain', 'France', 'Switzerland']

In [32]:
already_db = [id_[0] for id_ in ids]
#final_jobs.drop(final_jobs.where
already_db

['gd-1008978960599',
 'gd-1009145656832',
 'gd-1009194892055',
 'gd-1009378699438',
 'gd-1009378699686',
 'gd-1009378699688',
 'gd-1009387030740',
 'gd-1009387031469',
 'gd-1009387032269',
 'gd-1009396884857',
 'gd-1009398288471',
 'gd-1009422444983',
 'gd-1009422451765',
 'gd-1009422474231',
 'gd-1009425213039',
 'gd-1009467404167',
 'gd-1009480192342',
 'gd-1009499686898',
 'gd-1009647229411',
 'gd-1009647318253',
 'gd-1009647368719',
 'gd-1009647370389',
 'gd-1009647958079',
 'gd-1009648530978',
 'gd-1009648578094',
 'gd-1009648578099',
 'gd-1009648590120',
 'gd-1009648645405',
 'gd-1009648708313',
 'gd-1009648709672',
 'gd-1009648716279',
 'gd-1009648840864',
 'gd-1009648841974',
 'gd-1009648843362',
 'gd-1009648843880',
 'gd-1009648844191',
 'gd-1009648854663',
 'gd-1009648855448',
 'gd-1009648857243',
 'gd-1009648870834',
 'gd-1009648911971',
 'gd-1009648928288',
 'gd-1009648950467',
 'gd-1009648954490',
 'gd-1009648956221',
 'gd-1009648998550',
 'gd-1009649004741',
 'gd-1009649010167',
 'gd-1009649011172',
 'gd-1009649016583',
 'gd-1009649022648',
 'gd-1009649048938',
 'gd-1009649050641',
 'gd-1009649054081',
 'gd-1009649059048',
 'gd-1009649059874',
 'gd-1009649060109',
 'gd-1009649085290',
 'gd-1009649089413',
 'gd-1009649094650',
 'gd-1009649094657',
 'gd-1009649094659',
 'gd-1009649094665',
 'gd-1009649094667',
 'gd-1009649094670',
 'gd-1009649094671',
 'gd-1009649094672',
 'gd-1009649094674',
 'gd-1009649094675',
 'gd-1009649108553',
 'gd-1009649127647',
 'gd-1009649131223',
 'gd-1009649131771',
 'gd-1009649168464',
 'gd-1009649168592',
 'gd-1009649175685',
 'gd-1009649178276',
 'gd-1009649196961',
 'gd-1009649199392',
 'gd-1009649211831',
 'gd-1009649213210',
 'gd-1009649222842',
 'gd-1009649268916',
 'gd-1009649294280',
 'gd-1009649297379',
 'gd-1009649305830',
 'gd-1009649310872',
 'gd-1009649310873',
 'gd-1009649310875',
 'gd-1009649312927',
 'gd-1009649320732',
 'gd-1009649350457',
 'gd-1009649356611',
 'gd-1009649359424',
 'gd-1009649359427',
 'gd-1009649359429',
 'gd-1009649359431',
 'gd-1009649359435',
 'gd-1009649359436',
 'gd-1009649359437',
 'gd-1009649359439',
 'gd-1009649359443',
 'gd-1009649359445',
 'gd-1009649359446',
 'gd-1009649359447',
 'gd-1009649359448',
 'gd-1009649359450',
 'gd-1009649382071',
 'gd-1009649391533',
 'gd-1009649391767',
 'gd-1009649392679',
 'gd-1009649399186',
 'gd-1009649399362',
 'gd-1009649442536',
 'gd-1009649442562',
 'gd-1009649442870',
 'gd-1009649442886',
 'gd-1009649443104',
 'gd-1009649443113',
 'gd-1009649443253',
 'gd-1009649443332',
 'gd-1009649443621',
 'gd-1009649443739',
 'gd-1009649444054',
 'gd-1009649444862',
 'gd-1009649497117',
 'gd-1009649522040',
 'gd-1009649540775',
 'gd-1009649540793',
 'gd-1009649542501',
 'gd-1009649589937',
 'gd-1009649711297',
 'gd-1009649711617',
 'gd-1009649719384',
 'gd-1009649809876',
 'gd-1009649824127',
 'gd-1009649832043',
 'gd-1009649835301',
 'gd-1009649835346',
 'gd-1009649848275',
 'gd-1009649901341',
 'gd-1009649912964',
 'gd-1009649912965',
 'gd-1009649912968',
 'gd-1009649912972',
 'gd-1009649923751',
 'gd-1009649923945',
 'gd-1009649929914',
 'gd-1009649936332',
 'gd-1009649949632',
 'gd-1009649949633',
 'gd-1009649949635',
 'gd-1009649980223',
 'gd-1009649980933',
 'gd-1009649984657',
 'gd-1009649985545',
 'gd-1009649985551',
 'gd-1009649985683',
 'gd-1009649987116',
 'gd-1009649993560',
 'gd-1009649993579',
 'gd-1009649999199',
 'gd-1009650010343',
 'gd-1009650010371',
 'gd-1009650050053',
 'gd-1009650057284',
 'gd-1009650060884',
 'gd-1009650074103',
 'gd-1009650080339',
 'gd-1009650080882',
 'gd-1009650093300',
 'gd-1009650100743',
 'gd-1009650100749',
 'gd-1009650102017',
 'gd-1009650103292',
 'gd-1009650109848',
 'gd-1009650109866',
 'gd-1009650110162',
 'gd-1009650110163',
 'gd-1009650122644',
 'gd-1009650123172',
 'gd-1009650123178',
 'gd-1009650131642',
 'gd-1009650132368',
 'gd-1009650138683',
 'gd-1009650147578',
 'gd-1009650151276',
 'gd-1009650155041',
 'gd-1009650158309',
 'gd-1009650163633',
 'gd-1009650177190',
 'gd-1009650177192',
 'gd-1009650177195',
 'gd-1009650177197',
 'gd-1009650177198',
 'gd-1009650177204',
 'gd-1009650177205',
 'gd-1009650177207',
 'gd-1009650177209',
 'gd-1009650177214',
 'gd-1009650177215',
 'gd-1009650177216',
 'gd-1009650177218',
 'gd-1009650177219',
 'gd-1009650177220',
 'gd-1009650177221',
 'gd-1009650177222',
 'gd-1009650177223',
 'gd-1009650194046',
 'gd-1009650194048',
 'gd-1009650194224',
 'gd-1009650198497',
 'gd-1009650198500',
 'gd-1009650201017',
 'gd-1009650204160',
 'gd-1009650204892',
 'gd-1009650209574',
 'gd-1009650209776',
 'gd-1009650212550',
 'gd-1009650214087',
 'gd-1009650214217',
 'gd-1009650214886',
 'gd-1009650216400',
 'gd-1009650216420',
 'gd-1009650216816',
 'gd-1009650224746',
 'gd-1009650225897',
 'gd-1009650225963',
 'gd-1009650228639',
 'gd-1009650234509',
 'gd-1009650235067',
 'gd-1009650242537',
 'gd-1009650242539',
 'gd-1009650243084',
 'gd-1009650246567',
 'gd-1009650250563',
 'gd-1009650251868',
 'gd-1009650261868',
 'gd-1009650264797',
 'gd-1009650267066',
 'gd-1009650268324',
 'gd-1009650276218',
 'gd-1009650280530',
 'gd-1009650287618',
 'gd-1009650287619',
 'gd-1009650287626',
 'gd-1009650287640',
 'gd-1009650287921',
 'gd-1009650290328',
 'gd-1009650307895',
 'gd-1009650313052',
 'gd-1009650313840',
 'gd-1009650320623',
 'gd-1009650323448',
 'gd-1009650323452',
 'gd-1009650348409',
 'gd-1009650351907',
 'gd-1009650359817',
 'gd-1009650363802',
 'gd-1009650386290',
 'gd-1009650386428',
 'gd-1009650390983',
 'gd-1009650398832',
 'gd-1009650407274',
 'gd-1009650412463',
 'gd-1009650412464',
 'gd-1009650412465',
 'gd-1009650412466',
 'gd-1009650412467',
 'gd-1009650412468',
 'gd-1009650412470',
 'gd-1009650412475',
 'gd-1009650412477',
 'gd-1009650436079',
 'gd-1009650464330',
 'gd-1009650474820',
 'gd-1009650474912',
 'gd-1009650481601',
 'gd-1009650482270',
 'gd-1009650482301',
 'gd-1009650482324',
 'gd-1009650488376',
 'gd-1009650496688',
 'gd-1009650498371',
 'gd-1009650516078',
 'gd-1009650524461',
 'gd-1009650524462',
 'gd-1009650524464',
 'gd-1009650524466',
 'gd-1009650524467',
 'gd-1009650524469',
 'gd-1009650524473',
 'gd-1009650524474',
 'gd-1009650524475',
 'gd-1009650524476',
 'gd-1009650524479',
 'gd-1009650524481',
 'gd-1009650524521',
 'gd-1009650524523',
 'gd-1009650524538',
 'gd-1009650524539',
 'gd-1009650524555',
 'gd-1009650524558',
 'gd-1009650524572',
 'gd-1009650524574',
 'gd-1009650524587',
 'gd-1009650524593',
 'gd-1009650539100',
 'gd-1009650539689',
 'gd-1009650539690',
 'gd-1009650539693',
 'gd-1009650558049',
 'gd-1009650559915',
 'gd-1009650561973',
 'gd-1009650596825',
 'gd-1009650611300',
 'gd-1009650618778',
 'gd-1009650620342',
 'gd-1009650620380',
 'gd-1009650620915',
 'gd-1009650625612',
 'gd-1009650626966',
 'gd-1009650627949',
 'gd-1009650628223',
 'gd-1009650669093',
 'gd-1009650676627',
 'gd-1009650690569',
 'gd-1009650746716',
 'gd-1009650746717',
 'gd-1009650749536',
 'gd-1009650774242',
 'gd-1009650839201',
 'gd-1009650839232',
 'gd-1009650839424',
 'gd-1009650839830',
 'gd-1009650855248',
 'gd-1009650899044',
 'gd-1009650899300',
 'gd-1009650899546',
 'gd-1009650901434',
 'gd-1009650964232',
 'gd-1009650964370',
 'gd-1009650964515',
 'gd-1009650964646',
 'gd-1009650977580',
 'gd-1009651010828',
 'gd-1009651035855',
 'gd-1009651064322',
 'gd-1009651077598',
 'gd-1009651105873',
 'gd-1009651145271',
 'gd-1009651145664',
 'gd-1009651152072',
 'gd-1009651172607',
 'gd-1009651173953',
 'gd-1009651179507',
 'gd-1009651181366',
 'gd-1009651185134',
 'gd-1009651189133',
 'gd-1009651189526',
 'gd-1009651190570',
 'gd-1009651203388',
 'gd-1009651203965',
 'gd-1009651216955',
 'gd-1009651218302',
 'gd-1009651219956',
 'gd-1009651229691',
 'gd-1009651255833',
 'gd-1009651261412',
 'gd-1009651261413',
 'gd-1009651289007',
 'gd-1009651319263',
 'gd-1009651323574',
 'gd-1009651323596',
 'gd-1009651323882',
 'gd-1009651331729',
 'gd-1009651332298',
 'gd-1009651340469',
 'gd-1009651342875',
 'gd-1009651367005',
 'gd-1009651368558',
 'gd-1009651368559',
 'gd-1009651368571',
 'gd-1009651373134',
 'gd-1009651373861',
 'gd-1009651385096',
 'gd-1009651390310',
 'gd-1009651395337',
 'gd-1009651396602',
 'gd-1009651403027',
 'gd-1009651410105',
 'gd-1009651410126',
 'gd-1009651410138',
 'gd-1009651410179',
 'gd-1009651410208',
 'gd-1009651410228',
 'gd-1009651410287',
 'gd-1009651410956',
 'gd-1009651410994',
 'gd-1009651410996',
 'gd-1009651411059',
 'gd-1009651411500',
 'gd-1009651413731',
 'gd-1009651415366',
 'gd-1009651422682',
 'gd-1009651440506',
 'gd-1009651440511',
 'gd-1009651448825',
 'gd-1009651449210',
 'gd-1009651463387',
 'gd-1009651477309',
 'gd-1009651484235',
 'gd-1009651487348',
 'gd-1009651493275',
 'gd-1009651525363',
 'gd-1009651525603',
 'gd-1009651526693',
 'gd-1009651536550',
 'gd-1009651536552',
 'gd-1009651536553',
 'gd-1009651536559',
 'gd-1009651536562',
 'gd-1009651536564',
 'gd-1009651536565',
 'gd-1009651536569',
 'gd-1009651536571',
 'gd-1009651536573',
 'gd-1009651536577',
 'gd-1009651536578',
 'gd-1009651536580',
 'gd-1009651544336',
 'gd-1009651545176',
 'gd-1009651545402',
 'gd-1009651547656',
 'gd-1009651547664',
 'gd-1009651547669',
 'gd-1009651548105',
 'gd-1009651550786',
 'gd-1009651552903',
 'gd-1009651570190',
 'gd-1009651570191',
 'gd-1009651570195',
 'gd-1009651570435',
 'gd-1009651574321',
 'gd-1009651576681',
 'gd-1009651582473',
 'gd-1009651585823',
 'gd-1009651587692',
 'gd-1009651593146',
 'gd-1009651593660',
 'gd-1009651593703',
 'gd-1009651595395',
 'gd-1009651595690',
 'gd-1009651600164',
 'gd-1009651602214',
 'gd-1009651602556',
 'gd-1009651602893',
 'gd-1009651607786',
 'gd-1009651614300',
 'gd-1009651615590',
 'gd-1009651615645',
 'gd-1009651620221',
 'gd-1009651622259',
 'gd-1009651624738',
 'gd-1009651628739',
 'gd-1009651632503',
 'gd-1009651632520',
 'gd-1009651635958',
 'gd-1009651655845',
 'gd-1009651656436',
 'gd-1009651699779',
 'gd-1009651712898',
 'gd-1009651713023',
 'gd-1009651787107',
 'gd-1009651823934',
 'gd-1009651851785',
 'gd-1009651867409',
 'gd-1009651867410',
 'gd-1009651867411',
 'gd-1009651867412',
 'gd-1009651867418',
 'gd-1009651867420',
 'gd-1009651867430',
 'gd-1009651867431',
 'gd-1009651867432',
 'gd-1009651867435',
 'gd-1009651867438',
 'gd-1009651867439',
 'gd-1009651867442',
 'gd-1009651867443',
 'gd-1009651867446',
 'gd-1009651867449',
 'gd-1009651867450',
 'gd-1009651867451',
 'gd-1009651867452',
 'gd-1009651867453',
 'gd-1009651884861',
 'gd-1009651890753',
 'gd-1009651898046',
 'gd-1009651899611',
 'gd-1009651899924',
 'gd-1009651994574',
 'gd-1009651994675',
 'gd-1009651994722',
 'gd-1009651996198',
 'gd-1009651996840',
 'gd-1009651998189',
 'gd-1009652001555',
 'gd-1009652003705',
 'gd-1009652036751',
 'gd-1009652193627',
 'gd-1009652291547',
 'gd-1009652331296',
 'gd-1009652341027',
 'gd-1009652343452',
 'gd-1009652487772',
 'gd-1009652556576',
 'gd-1009652595423',
 'gd-1009652595729',
 'gd-1009652595744',
 'gd-1009652595746',
 'gd-1009652607658',
 'gd-1009652611733',
 'gd-1009652620542',
 'gd-1009652627992',
 'gd-1009652630227',
 'gd-1009652633585',
 'gd-1009652790424',
 'gd-1009652794703',
 'gd-1009652808664',
 'gd-1009652835878',
 'gd-1009652862738',
 'gd-1009652862752',
 'gd-1009652862781',
 'gd-1009652863185',
 'gd-1009652863207',
 'gd-1009652872678',
 'gd-1009652899837',
 'gd-1009652902443',
 'gd-1009652907860',
 'gd-1009652962297',
 'gd-1009652963343',
 'gd-1009652992405',
 'gd-1009653001448',
 'gd-1009653005510',
 'gd-1009653012133',
 'gd-1009653031664',
 'gd-1009653032386',
 'gd-1009653042134',
 'gd-1009653053276',
 'gd-1009653055165',
 'gd-1009653055319',
 'gd-1009653061768',
 'gd-1009653082196',
 'gd-1009653089195',
 'gd-1009653100779',
 'gd-1009653107613',
 'gd-1009653107894',
 'gd-1009653108838',
 'gd-1009653110263',
 'gd-1009653114409',
 'gd-1009653114410',
 'gd-1009653130867',
 'gd-1009653155535',
 'gd-1009653158557',
 'gd-1009653161246',
 'gd-1009653162218',
 'gd-1009653162222',
 'gd-1009653162224',
 'gd-1009653163106',
 'gd-1009653167400',
 'gd-1009653168074',
 'gd-1009653168214',
 'gd-1009653168283',
 'gd-1009653171841',
 'gd-1009653173955',
 'gd-1009653176672',
 'gd-1009653176805',
 'gd-1009653179097',
 'gd-1009653184814',
 'gd-1009653201327',
 'gd-1009653206130',
 'gd-1009653206503',
 'gd-1009653209573',
 'gd-1009653213781',
 'gd-1009653220302',
 'gd-1009653234476',
 'gd-1009653236101',
 'gd-1009653245744',
 'gd-1009653249555',
 'gd-1009653249565',
 'gd-1009653256867',
 'gd-1009653260802',
 'gd-1009653261457',
 'gd-1009653261992',
 'gd-1009653267623',
 'gd-1009653276385',
 'gd-1009653277476',
 'gd-1009653277479',
 'gd-1009653277480',
 'gd-1009653277481',
 'gd-1009653277482',
 'gd-1009653277485',
 'gd-1009653277486',
 'gd-1009653277487',
 'gd-1009653277488',
 'gd-1009653277489',
 'gd-1009653277490',
 'gd-1009653277492',
 'gd-1009653277495',
 'gd-1009653277496',
 'gd-1009653302422',
 'gd-1009653303428',
 'gd-1009653310306',
 'gd-1009653312528',
 'gd-1009653312901',
 'gd-1009653315017',
 'gd-1009653320536',
 'gd-1009653320771',
 'gd-1009653342080',
 'gd-1009653349417',
 'gd-1009653352799',
 'gd-1009653370732',
 'gd-1009653370767',
 'gd-1009653378885',
 'gd-1009653413784',
 'gd-1009653424075',
 'gd-1009653434885',
 'gd-1009653436272',
 'gd-1009653446815',
 'gd-1009653474684',
 'gd-1009653485448',
 'gd-1009653489357',
 'gd-1009653491310',
 'gd-1009653491328',
 'gd-1009653492238',
 'gd-1009653492252',
 'gd-1009653493315',
 'gd-1009653503842',
 'gd-1009653522042',
 'gd-1009653522199',
 'gd-1009653523984',
 'gd-1009653524115',
 'gd-1009653524117',
 'gd-1009653524121',
 'gd-1009653524128',
 'gd-1009653558365',
 'gd-1009653564710',
 'gd-1009653570019',
 'gd-1009653570110',
 'gd-1009653570116',
 'gd-1009653570322',
 'gd-1009653573235',
 'gd-1009653573674',
 'gd-1009653573937',
 'gd-1009653574586',
 'gd-1009653575612',
 'gd-1009653578004',
 'gd-1009653609364',
 'gd-1009653619263',
 'gd-1009653619264',
 'gd-1009653619267',
 'gd-1009653619272',
 'gd-1009653619274',
 'gd-1009653619276',
 'gd-1009653619280',
 'gd-1009653619281',
 'gd-1009653619283',
 'gd-1009653619286',
 'gd-1009653619287',
 'gd-1009653619288',
 'gd-1009653619289',
 'gd-1009653619292',
 'gd-1009653619297',
 'gd-1009653626294',
 'gd-1009653638705',
 'gd-1009653638735',
 'gd-1009653641378',
 'gd-1009653641603',
 'gd-1009653641988',
 'gd-1009653642827',
 'gd-1009653653115',
 'gd-1009653666305',
 'gd-1009653728622',
 'gd-1009653735486',
 'gd-1009653758651',
 'gd-1009653775972',
 'gd-1009653928642',
 'gd-1009654008980',
 'gd-1009654043860',
 'gd-1009654044918',
 'gd-1009654044923',
 'gd-1009654044982',
 'gd-1009654045839',
 'gd-1009654046658',
 'gd-1009654046895',
 'gd-1009654047976',
 'gd-1009654049499',
 'gd-1009654255530',
 'gd-1009654263195',
 'gd-1009654273890',
 'gd-1009654283292',
 'gd-1009654292132',
 'gd-1009654303911',
 'gd-1009654339498',
 'gd-1009654347026',
 'gd-1009654347027',
 'gd-1009654379499',
 'gd-1009654412098',
 'gd-1009654420151',
 'gd-1009654424533',
 'gd-1009654433487',
 'gd-1009654444990',
 'gd-1009654452788',
 'gd-1009654456765',
 'gd-1009654483365',
 'gd-1009654558789',
 'gd-1009654578664',
 'gd-1009654596125',
 'gd-1009654688403',
 'gd-1009654708324',
 'gd-1009654839517',
 'gd-1009654908204',
 'gd-1009654946890',
 'gd-1009655024113',
 'gd-1009655028240',
 'gd-1009655090123',
 'gd-1009655099561',
 'gd-1009655193072',
 'gd-1009655289915',
 'gd-1009655750716',
 'gd-1009655779400',
 'gd-1009655779467',
 'gd-1009655932962',
 'gd-1009655997427',
 'gd-1009656123228',
 'gd-1009656679239',
 'gd-1009656679365',
 'gd-1009656694379',
 'gd-1009656694383',
 'gd-1009656812370',
 'gd-1009657068683',
 'gd-1009657127986',
 'gd-1009657353686',
 'gd-1009657404346',
 'gd-1009657561842',
 'gd-1009657894474',
 'gd-1009657943176',
 'gd-1009658263199',
 'gd-1009658309732',
 'gd-1009658355750',
 'gd-1009658473646',
 'gd-1009658548916',
 'gd-1009658559939',
 'gd-1009658564985',
 'gd-1009658573301',
 'gd-1009658578012',
 'gd-1009658588275',
 'gd-1009658588643',
 'gd-1009658598256',
 'gd-1009658599962',
 'gd-1009658633258',
 'gd-1009658684595',
 'gd-1009658690934',
 'gd-1009658694985',
 'gd-1009658726548',
 'gd-1009658733177',
 'gd-1009658816475',
 'gd-1009658831199',
 'gd-1009658880752',
 'gd-1009658910397',
 'gd-1009658973217',
 'gd-1009658973266',
 'gd-1009658979505',
 'gd-1009659000737',
 'gd-1009659076867',
 'gd-1009659141089',
 'gd-1009659189167',
 'gd-1009659215789',
 'gd-1009659261625',
 'gd-1009659261956',
 'gd-1009659348351',
 'gd-1009659383457',
 'gd-1009659385560',
 'gd-1009659560767',
 'gd-1009659967971',
 'gd-1009660003216',
 'gd-1009660004526',
 'gd-1009660058531',
 'gd-1009660079815',
 'gd-1009660081674',
 'gd-1009660081677',
 'gd-1009660087482',
 'gd-1009660089429',
 'gd-1009660115189',
 'gd-1009660131921',
 'gd-1009660137022',
 'gd-1009660137075',
 'gd-1009660137361',
 'gd-1009660140095',
 'gd-1009660158620',
 'gd-1009660189088',
 'gd-1009660218061',
 'gd-1009660228133',
 'gd-1009660257272',
 'gd-1009660257277',
 'gd-1009660275337',
 'gd-1009660299615',
 'gd-1009660332738',
 'gd-1009660341480',
 'gd-1009660351277',
 'gd-1009660394953',
 'gd-1009660512503',
 'gd-1009660515037',
 'gd-1009660528331',
 'gd-1009660549563',
 'gd-1009660570402',
 'gd-1009660661837',
 'gd-1009660661839',
 'gd-1009660947281',
 'gd-1009660947340',
 'gd-1009661027067',
 'gd-1009661165299',
 'gd-1009661274224',
 'gd-1009661314668',
 'gd-1009661315777',
 'gd-1009661418879',
 'gd-1009661515051',
 'gd-1009661528576',
 'gd-1009661567494',
 'gd-1009661581251',
 'gd-1009661584653',
 'gd-1009661626630',
 'gd-1009661630932',
 'gd-1009661633962',
 'gd-1009661648271',
 'gd-1009661726043',
 'gd-1009661757896',
 'gd-1009661770773',
 'gd-1009661772415',
 'gd-1009661772711',
 'gd-1009661772743',
 'gd-1009661824630',
 'gd-1009661836745',
 'gd-1009661864277',
 'gd-1009661894782',
 'gd-1009661987044',
 'gd-1009662078587',
 'gd-1009662078589',
 'gd-1009662081562',
 'gd-1009662592753',
 'gd-1009662904436',
 'gd-1009662927680',
 'gd-1009662927695',
 'gd-1009663108376',
 'gd-1009663183443',
 'gd-1009663193771',
 'gd-1009663299505',
 'gd-1009663337490',
 'gd-1009663353535',
 'gd-1009663370231',
 'gd-1009663431078',
 'gd-1009663432367',
 'gd-1009663475655',
 'gd-1009663493574',
 'gd-1009663511137',
 'gd-1009663696942',
 'gd-1009663778784',
 'gd-1009663887608',
 'gd-1009663952729',
 'gd-1009664134443',
 'gd-1009664311482',
 'gd-1009664423747',
 'gd-1009664424565',
 'gd-1009664425251',
 'gd-1009664557911',
 'gd-1009664603335',
 'gd-1009664622187',
 'gd-1009664626532',
 'gd-1009664645083',
 'gd-1009664673567',
 'gd-1009664677041',
 'gd-1009664677054',
 'gd-1009664692947',
 'gd-1009664708895',
 'gd-1009664730925',
 'gd-1009664732692',
 'gd-1009664762737',
 'gd-1009664782917',
 'gd-1009664784506',
 'gd-1009664789135',
 'gd-1009664794368',
 'gd-1009664804188',
 'gd-1009664808911',
 'gd-1009664898733',
 'gd-1009664909369',
 'gd-1009664935509',
 'gd-1009664943445',
 'gd-1009664963713',
 'gd-1009664967091',
 'gd-1009664967130',
 'gd-1009664990296',
 'gd-1009665044551',
 'gd-1009665286468',
 'gd-1009665288539',
 'gd-1009665289110',
 'gd-1009665307309',
 'gd-1009665319316',
 'gd-1009665338382',
 'gd-1009665361320',
 'gd-1009665478317',
 'gd-1009666904222',
 'gd-1009667136904',
 'gd-1009667147596',
 'gd-1009667211850',
 'gd-1009667261024',
 'gd-1009667271960',
 'gd-1009667328921',
 'gd-1009667329818',
 'gd-1009667514004',
 'gd-1009667632870',
 'gd-1009667635039',
 'gd-1009667639771',
 'gd-1009667694989',
 'gd-1009667695036',
 'gd-1009667717743',
 'gd-1009667721068',
 'gd-1009667753019',
 'gd-1009667774644',
 'gd-1009667777604',
 'gd-1009667824919',
 'gd-1009667993975',
 'gd-1009668008250',
 'gd-1009668021962',
 'gd-1009668082738',
 'gd-1009668184601',
 'gd-1009668480610',
 'gd-1009668581656',
 'gd-1009668676196',
 'gd-1009668764352',
 'gd-1009668822880',
 'gd-1009668875648',
 'gd-1009668904467',
 'gd-1009668905065',
 'gd-1009668959663',
 'gd-1009668969340',
 'gd-1009668969344',
 'gd-1009669040791',
 'gd-1009669053325',
 'gd-1009669056496',
 'gd-1009669082404',
 'gd-1009669109968',

In [33]:
final_jobs['id'].isin(already_db)

0      False
4      False
8      False
9      False
10     False
       ...
351    False
352    False
353    False
354    False
355    False
Name: id, Length: 243, dtype: bool

In [39]:
final_jobs[['id', 'description']]

                      id                                        description
0       gd-1009670311645  westcon-comstor (westcongroup inc.) is a globa...
4       gd-1009670933847  the barcelona institute for global health (isg...
8       gd-1009670821913  we are looking for someone with strong analyti...
9       gd-1009670584344  eurecat -   eurecat is the main research & tec...
10      gd-1009670390004  our story   strada is a technology-enabled, pe...
..                   ...                                                ...
351  in-12d536e509f9f519  postdoctoral research position focused on atom...
352  in-767c71d0a79dcc6f  we are looking for a webtech technical lead se...
353  in-fe3316838d5ebcac  - experience (non-internship) in professional ...
354  in-50c9b8f62d2a9be7  the data engineer supports the data team to dr...
355  in-34cb4fc4ad2cd826  - bachelor's degree - knowledge of engineering...

[243 rows x 2 columns]

In [364]:
final_jobs.loc[final_jobs['id'].isin(already_db)].index

Index([], dtype='int64')

In [ ]:
already_db

In [ ]:
final_jobs

In [ ]:
# Check if IDs already exist in the database before adding:

final_jobs.to_sql(
    "jobspy",
    conn,
    if_exists='append',
    index=False,
)

In [ ]:
%load_ext sql
%sql sqlite:///jobs.db
%config SqlMagic.style = '_DEPRECATED_DEFAULT'

In [ ]:
%sql SELECT * FROM jobspy;

In [ ]:
from collections import Counter
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import pandas as pd

# Fetch all job descriptions
df = pd.read_sql_query("SELECT * FROM jobspy", conn)

# Count words in all descriptions
all_text = " ".join(df["description"]).lower().split()
word_freq = Counter(all_text)

# Convert to DataFrame for easy plotting
word_freq_df = pd.DataFrame(word_freq.items(), columns=["Word", "Count"])
word_freq_df = word_freq_df.sort_values(by="Count", ascending=False)

# Plot word cloud
wordcloud = WordCloud(width=800, height=400, background_color="white").generate_from_frequencies(word_freq)
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()

## Wordcount and various data extraction from job description

Now we have the cleaned dataframe for the output query. This would be the transformation stage that happens BEFORE visualization? The questions that the dashboard should answer are the following:

* How often are different cloud technologies mentioned in the job descriptions? (FuzzyWuzzy, AWS, GCP, AZURE)
* Programming languages?
* Is experience mentioned?
* How similar are the ads between them?
* Word frequency in job title?

In [ ]:
word_freq_df.loc[word_freq_df['Word']=="cloud"]

In [ ]:
word_freq_df

In [ ]:
import spacy

nlp = spacy.load("en_core_web_md")
text = final_jobs['description'].iloc[0]
doc = nlp(text)

In [414]:
def convert_description(text):
    nlp = spacy.load("en_core_web_sm")
    doc = nlp(text)
    words = [token.lemma_ for token in doc if token.is_alpha and not token.is_stop]  # Lemmatization & stopword removal
    return words

In [417]:
final_jobs['description']=final_jobs['description'].apply(convert_description)

In [428]:
final_jobs['python'] = final_jobs['description'].apply(lambda x: 'python' in x)
final_jobs['python'].loc[final_jobs['python']==True].count()/final_jobs.shape[0]

0.3223684210526316

In [432]:
final_jobs['cloud'] = final_jobs['description'].apply(lambda x: 'cloud' in x)
final_jobs['cloud'].loc[final_jobs['cloud']==True].count()/final_jobs.shape[0]

0.3157894736842105

In [429]:
final_jobs['experience'] = final_jobs['description'].apply(lambda x: 'experience' in x)
final_jobs['experience'].loc[final_jobs['experience']==True].count()/final_jobs.shape[0]

0.993421052631579

In [418]:
final_jobs['description'].iloc[0]

['description',
 'energy',
 'storage',
 'procurement',
 'specialist',
 'company',
 'eosol',
 'group',
 'location',
 'madrid',
 'experience',
 'minimum',
 'year',
 'eosol',
 'group',
 'eosol',
 'group',
 'forefront',
 'innovative',
 'energy',
 'solution',
 'commit',
 'deliver',
 'sustainable',
 'energy',
 'solution',
 'drive',
 'efficiency',
 'performance',
 'reliability',
 'position',
 'overview',
 'energy',
 'storage',
 'procurement',
 'specialist',
 'play',
 'pivotal',
 'role',
 'shape',
 'procurement',
 'strategy',
 'underpin',
 'energy',
 'storage',
 'project',
 'lead',
 'tender',
 'process',
 'coordinate',
 'internal',
 'external',
 'stakeholder',
 'ensure',
 'procurement',
 'activity',
 'align',
 'eosol',
 'group',
 'objective',
 'position',
 'require',
 'individual',
 'strong',
 'background',
 'procurement',
 'project',
 'management',
 'techno',
 'economic',
 'analysis',
 'keen',
 'understanding',
 'energy',
 'storage',
 'landscape',
 'key',
 'responsibility',
 'work',
 'directly',
 'responsible',
 'energy',
 'storage',
 'procurement',
 'theprocurement',
 'department',
 'lead',
 'tendering',
 'process',
 'request',
 'proposal',
 'rfps',
 'coordinate',
 'department',
 'collect',
 'relevant',
 'input',
 'engineering',
 'input',
 'input',
 'business',
 'development',
 'etc',
 'carry',
 'techno',
 'economical',
 'comparison',
 'bench',
 'mark',
 'carry',
 'lco',
 'analysis',
 'base',
 'establish',
 'timeline',
 'lead',
 'coordinate',
 'different',
 'project',
 'stakeholder',
 'epc',
 'battery',
 'supplier',
 'inverter',
 'supplier',
 'etc',
 'internal',
 'department',
 'allow',
 'smooth',
 'tendering',
 'contracting',
 'process',
 'lead',
 'coordinate',
 'division',
 'responsibility',
 'different',
 'party',
 'alignment',
 'correct',
 'project',
 'timing',
 'lead',
 'support',
 'contract',
 'development',
 'process',
 'prepare',
 'support',
 'material',
 'project',
 'update',
 'meeting',
 'executive',
 'committee',
 'support',
 'improvement',
 'exist',
 'internal',
 'tool',
 'tender',
 'evaluation',
 'qualification',
 'bachelor',
 'degree',
 'complete',
 'master',
 'degree',
 'field',
 'engineering',
 'computer',
 'science',
 'datum',
 'economic',
 'mathematic',
 'statistic',
 'business',
 'management',
 'previous',
 'experience',
 'tendering',
 'process',
 'project',
 'development',
 'renewable',
 'energy',
 'energy',
 'storage',
 'industry',
 'ability',
 'work',
 'project',
 'simultaneously',
 'balance',
 'priority',
 'independently',
 'keen',
 'learn',
 'develop',
 'skill',
 'field',
 'renewable',
 'energy',
 'particularly',
 'battery',
 'technology',
 'passion',
 'renewable',
 'energy',
 'industry',
 'combine',
 'solid',
 'analytical',
 'skill',
 'critical',
 'thinking',
 'good',
 'level',
 'microsoft',
 'office',
 'word',
 'excel',
 'powerpoint',
 'ms',
 'project',
 'advantage',
 'highly',
 'organize',
 'sense',
 'order',
 'able',
 'follow',
 'number',
 'project',
 'task',
 'time',
 'communicate',
 'key',
 'result',
 'manager',
 'verbal',
 'visual',
 'write',
 'medium',
 'spanish',
 'english',
 'high',
 'glass',
 'half',
 'attitude',
 'open',
 'mind',
 'appetite',
 'look',
 'process',
 'improvement',
 'implementation',
 'new',
 'solution',
 'offer',
 'term',
 'contract',
 'flexible',
 'schedule',
 'day',
 'remote',
 'working']

In [ ]:
from spacy.matcher import Matcher

matcher = Matcher(nlp.vocab)
pattern = [
    {"POS": "NOUN"},
    {"POS": "NOUN", "LEMMA": "language"},
    {"POS": "NOUN", "OP": "+"}
]
matcher.add("Experience", [pattern])
matches = matcher(doc)

In [ ]:
matches

In [ ]:
for token in doc:
    print(token.text, token.lemma_, token.pos_)

In [ ]:
import networkx as nx
import matplotlib.pyplot as plt
from collections import Counter
from itertools import combinations

# Preprocessing: Tokenize and filter words
word_counts = Counter()
word_pairs = Counter()

#for text in texts:
doc = nlp(text.lower())
words = [token.lemma_ for token in doc if token.is_alpha and not token.is_stop]  # Lemmatization & stopword removal
word_counts.update(words)  # Count individual word occurrences
#Extract consecutive word pairs
for i in range(len(words) - 1):
    pair = (words[i], words[i + 1])  # Only take consecutive words
    word_pairs[pair] += 1

# Create a Graph
G = nx.Graph()

# Add edges with weights
for (word1, word2), count in word_pairs.items():
    G.add_edge(word1, word2, weight=count)

# Scale node sizes based on frequency
node_sizes = [word_counts[word] * 500 for word in G.nodes()]  # Scale factor for better visualization

# Draw the graph
plt.figure(figsize=(8, 6))
pos = nx.spring_layout(G, seed=42)  # Position nodes for visualization
nx.draw(G, pos, with_labels=True, node_color="lightblue", edge_color="gray", 
        node_size=node_sizes, font_size=10, alpha=0.7)

# Add edge labels (weights)
edge_labels = {(word1, word2): count for (word1, word2), count in pair_counts.items()}
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels)

plt.title("Consecutive Word Co-occurrence Graph")
plt.show()

In [ ]:
word_pairs

In [ ]:
import plotly.graph_objects as go

G = nx.Graph()

for (word1, word2), count in word_pairs.items():
    G.add_edge(word1, word2, weight=count)

# Get positions using spring layout
pos = nx.spring_layout(G, seed=42)

# Extract data for Plotly
edge_x, edge_y, edge_text = [], [], []
for edge in G.edges(data=True):
    x0, y0 = pos[edge[0]]
    x1, y1 = pos[edge[1]]
    edge_x.extend([x0, x1, None])  # None for breaks in line
    edge_y.extend([y0, y1, None])
    edge_text.append(f"{edge[0]} ↔ {edge[1]} (Weight: {edge[2]['weight']})")

# Node data
node_x, node_y, node_size, node_text = [], [], [], []
for node in G.nodes():
    x, y = pos[node]
    node_x.append(x)
    node_y.append(y)
    node_size.append(word_counts[node] * 10)  # Scale node size
    node_text.append(f"{node} (Count: {word_counts[node]})")

# Create edge trace
edge_trace = go.Scatter(
    x=edge_x, y=edge_y,
    line=dict(width=1, color="gray"),
    hoverinfo="text",
    text=edge_text,
    mode="lines"
)

# Create node trace
node_trace = go.Scatter(
    x=node_x, y=node_y,
    mode="markers+text",
    marker=dict(size=node_size, color="lightblue", line=dict(width=2, color="black")),
    text=node_text,
    hoverinfo="text",
    textposition="top center"
)

# Create interactive Plotly figure
fig = go.Figure(data=[edge_trace, node_trace])
fig.update_layout(
    title="Interactive Word Co-occurrence Graph",
    showlegend=False,
    hovermode="closest",
    margin=dict(b=20, l=5, r=5, t=40),
    xaxis=dict(showgrid=False, zeroline=False, showticklabels=False),
    yaxis=dict(showgrid=False, zeroline=False, showticklabels=False)
)

# Show interactive graph
fig.show()